### ISSUE TITLE
Compilation Error on Ubuntu 18.04 ( 

### ISSUE THREAD

**Issue by sroycode** [matrix-construct/construct#165]
Hi:

On Ubuntu 18.04 , configured with "./configure --with-included-rocksdb --with-included-boost  --prefix=${HOME}/.local", 
libicu-dev version  60.2-3ubuntu3.1

I am getting the following error in "make"

```
In file included from /usr/include/unicode/utf.h:217:0,
                 from /usr/include/unicode/utypes.h:44,
                 from /usr/include/unicode/uchar.h:28,
                 from icu.cc:16:
icu.cc: In function ‘size_t ircd::icu::utf8::decode(char32_t* const&, const size_t&, const ircd::string_view&)’:
icu.cc:317:3: error: cannot convert ‘size_t* {aka long unsigned int*}’ to ‘int32_t* {aka int*}’ for argument ‘2’ to ‘UChar32 utf8_nextCharSafeBody_60(const uint8_t*, int32_t*, int32_t, UChar32, UBool)’
   U8_NEXT(_in, off, size(in), out[ret]);
   ^
make[1]: *** [icu.lo] Error 1
make: *** [all-recursive] Error 1

```

**Comment by jevolk** [comment]
It looks like you're missing libicu. I don't have the exact package name
but it might be libicu-dev or libicuuc-dev.

It turns out this package should be optional and that code shouldn't be
compiled when it's not available, so I will fix that.

**Comment by sroycode** [comment]
libicu-dev version 60.2-3ubuntu3.1 is already there , is there a version related issue ?

**Comment by jevolk** [comment]
Sorry for jumping the gun. Do you have some information about your platform and versions for libicu? Also unfortunately Ubuntu 18.04 is no longer really tested here as we're developing on 20.04 now, but it was used for a long time and did work. I'd like to get to the bottom of this and keep it working.

**Comment by jevolk** [comment]
I pushed a potential fix to my staging repository at https://github.com/jevolk/charybdis.git but I haven't tested it with your libicu version 60.2 (I'm using 66.1 here). Feel free to pull master from this repository and report if there are additional compilation errors beyond this.

**Comment by sroycode** [comment]
Hi:
Charybdis went through on that step, gave another error:
```
utf.cc:261:59: error: explicit qualification in declaration of ‘ircd::simd::u8x16 ircd::utf16::find_surrogate(ircd::simd::u8x16)’
  template u8x16 utf16::find_surrogate<u8x16>(const u8x16) noexcept;
                                                           ^~~~~~~~
utf.cc:262:59: error: explicit qualification in declaration of ‘ircd::simd::u8x32 ircd::utf16::find_surrogate(ircd::simd::u8x32)’
  template u8x32 utf16::find_surrogate<u8x32>(const u8x32) noexcept;
                                                           ^~~~~~~~
utf.cc:263:59: error: explicit qualification in declaration of ‘ircd::simd::u8x64 ircd::utf16::find_surrogate(ircd::simd::u8x64)’
  template u8x64 utf16::find_surrogate<u8x64>(const u8x64) noexcept;
```

**Comment by jevolk** [comment]
Thanks! What compiler version?

**Comment by sroycode** [comment]
> Thanks! What compiler version?

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by jevolk** [comment]
> > Thanks! What compiler version?
> 
> gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Yes, unfortunately this is a bit too old at this point. If you try to `export CXX=g++-8` and then reconfigure that should work on Ubuntu 18.04. As an aside, you may need to `git clean -f -x -d` before running configure again (though you may not, but we've had reports of trouble when performing similar things).

**Comment by sroycode** [comment]
With g++8 , the error now is
```
db_allocator.cc:28:40: error: ‘extent_hooks_t’ was not declared in this scope
  static void *cache_arena_handle_alloc(extent_hooks_t *, void *, size_t, size_t, bool *, bool *, uint) noexcept;
                                        ^~~~~~~~~~~~~~
db_allocator.cc:28:56: error: expected primary-expression before ‘,’ token
  static void *cache_arena_handle_alloc(extent_hooks_t *, void *, size_t, size_t, bool *, bool *, uint) noexcept;
                                                       ^
```


For installing g++8 on ubuntu 8 the following was used:

```
sudo apt install software-properties-common
sudo apt install gcc-7 g++-7 gcc-8 g++-8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7
```

**Comment by jevolk** [comment]
Thanks, looks like a jemalloc issue now. Do you have jemalloc installed? I'm looking into how/why that code is being #ifdef'ed into the build.

**Comment by rodneyrod** [comment]
Getting the same utf8 error, using clang as the compiler per the Build guide

**Comment by jevolk** [comment]
The goalposts have shifted a bit, but this is not produced by our current build matrix with clang-14+ and gcc-10+. Thank you all for reporting :pray:
